#!/usr/bin/env python3
"""
Extract individual German-Turkish word pairs from sentence JSON files.
- Reads: upload/brief.json, upload/bild.json, upload/bild-erfahrung.json
- For each unique German word appearing in the sentences, looks up its Turkish
  translation from a curated B1-level German→Turkish dictionary embedded below.
- Writes: src/lib/word-vocabulary.json
- DOES NOT modify the original JSON files.
"""

import json
import re
from pathlib import Path
from collections import Counter

BASE = Path(__file__).resolve().parent.parent
UPLOAD = BASE / "upload"
OUT = BASE / "src" / "lib" / "word-vocabulary.json"

# ───────────────────────────────────────────────────────────────────────────────
# Curated German → Turkish dictionary (B1 level, common words appearing in
# letter-writing and image-description contexts)
# ───────────────────────────────────────────────────────────────────────────────
GERMAN_TR_DICT = {
    # ─── Greetings / openers ───
    "Zuerst": "Öncelikle",
    "hoffe": "umuyorum",
    "alles": "her şey",
    "gut": "iyi",
    "läuft": "gidiyor",
    "lange": "uzun",
    "gesehen": "gördük",
    "gefreut": "mutlu oldum",
    "gehört": "duydum",
    "wieder": "tekrar",
    "hören": "duymak",
    "gute": "iyi",
    "Nachricht": "haber",
    "schön": "güzel",
    "Tag": "gün",
    "wünschen": "dilemek",
    "Schönen": "Güzel",
    "geht": "nasıl",
    "Hoffe": "Umarım",
    "Wie": "Nasıl",
    "Hallo": "Merhaba",

    # ─── Writing/email verbs ───
    "schreibe": "yazıyorum",
    "schreiben": "yazmak",
    "Schreibe": "Yazıyorum",
    "E-Mail": "e-posta",
    "Brief": "mektup",
    "Nachricht": "haber",
    "gehört": "duydum",
    "erreichen": "ulaşmak",
    "erreiche": "ulaşıyorum",
    "angerufen": "aradım",
    "anrufen": "aramak",
    "telefonisch": "telefonla",
    "Firma": "şirket",
    "Leute": "insanlar",
    "niemanden": "kimseyi",
    "deshalb": "bu yüzden",
    "deshalb": "bu nedenle",
    "deshalb": "bundan dolayı",

    # ─── Family ───
    "Frau": "kadın/bayan",
    "Mann": "adam/erkek",
    "Sohn": "oğul",
    "Tochter": "kız evlat",
    "Kind": "çocuk",
    "Kinder": "çocuklar",
    "Mutter": "anne",
    "Vater": "baba",
    "Eltern": "ebeveyn",
    "Geschwister": "kardeşler",
    "Bruder": "erkek kardeş",
    "Schwester": "kız kardeş",
    "Onkel": "amca/dayı",
    "Tante": "teyze/hala",
    "Großvater": "büyükbaba",
    "Großmutter": "büyükanne",
    "Familie": "aile",
    "Familien": "aileler",
    "Ehefrau": "eş",
    "Ehemann": "koca",
    "Verwandte": "akraba",

    # ─── Communication ───
    "Frage": "soru",
    "Fragen": "sorular",
    "fragen": "sormak",
    "Antwort": "yanıt",
    "antworten": "yanıtlamak",
    "sagen": "söylemek",
    "sage": "söylüyorum",
    "erzählen": "anlatmak",
    "erzähle": "anlatıyorum",
    "bescheid": "bilgi",
    "Bescheid": "bilgi",
    "mitteilen": "bildirmek",
    "teile": "bildiriyorum",
    "teilen": "bildirmek",
    "informieren": "bilgilendirmek",
    "informiert": "bilgilendirir",
    "melden": "haber vermek",
    "melden": "bildirmek",
    "melden": "haber veriyorum",
    "hören": "duymak",
    "höre": "duyuyorum",
    "reden": "konuşmak",
    "sprechen": "konuşmak",
    "spricht": "konuşur",
    "Gespräch": "konuşma",
    "Vorstellungsgespräch": "mülakat",
    "Gespräch": "görüşme",

    # ─── Helpers / auxiliaries ───
    "möchte": "istiyorum",
    "möchten": "istiyorlar",
    "will": "istiyor",
    "wollen": "istemek",
    "brauche": "ihtiyacım var",
    "brauchen": "ihtiyaç",
    "habe": "sahibim",
    "haben": "sahip",
    "hat": "sahip",
    "kann": "edebilirim",
    "können": "edebilmek",
    "könnten": "edebilir miydiniz",
    "könnte": "edebilirim",
    "muss": "zorundayım",
    "müssen": "zorunda",
    "soll": "gerek",
    "sollen": "gerekli",
    "dürfen": "izin",
    "darf": "edebilir miyim",
    "wird": "olacak",
    "werden": "olmak",
    "wurde": "oldu",
    "wurden": "oldular",
    "sein": "olmak",
    "ist": "dır",
    "sind": "dirler",
    "war": "idi",
    "waren": "idiler",

    # ─── Time / dates ───
    "heute": "bugün",
    "morgen": "yarın",
    "gestern": "dün",
    "Woche": "hafta",
    "Wochenende": "hafta sonu",
    "Wochen": "haftalar",
    "Tag": "gün",
    "Tage": "günler",
    "Monat": "ay",
    "Monate": "aylar",
    "Jahr": "yıl",
    "Jahre": "yıllar",
    "Stunde": "saat",
    "Stunden": "saatler",
    "Minute": "dakika",
    "Minuten": "dakikalar",
    "Uhr": "saat",
    "Uhr": "zaman",
    "Mai": "Mayıs",
    "Januar": "Ocak",
    "Februar": "Şubat",
    "März": "Mart",
    "April": "Nisan",
    "Juni": "Haziran",
    "Juli": "Temmuz",
    "August": "Ağustos",
    "September": "Eylül",
    "Oktober": "Ekim",
    "November": "Kasım",
    "Dezember": "Aralık",
    "Montag": "Pazartesi",
    "Dienstag": "Salı",
    "Mittwoch": "Çarşamba",
    "Donnerstag": "Perşembe",
    "Freitag": "Cuma",
    "Samstag": "Cumartesi",
    "Sonntag": "Pazar",
    "morgens": "sabahleyin",
    "vormittags": "öğleden önce",
    "mittags": "öğleyin",
    "nachmittags": "öğleden sonra",
    "abends": "akşamleyin",
    "nachts": "geceleyin",
    "früh": "erken",
    "spät": "geç",
    "jetzt": "şimdi",
    "bald": "yakında",
    "später": "sonra",
    "danach": "ondan sonra",
    "zuerst": "önce",
    "zuletzt": "en son",
    "damals": "o zaman",
    "damals": "o sırada",
    "Pandemie": "pandemi",
    "während": "sırasında",
    "während": "esnasında",

    # ─── School / work ───
    "Schule": "okul",
    "Unterricht": "ders",
    "Kurs": "kurs",
    "Studium": "üniversite eğitimi",
    "studiert": "okudu",
    "studieren": "okumak",
    "Universität": "üniversite",
    "Gymnasium": "lise",
    "Kindergarten": "anaokulu",
    "Lehrer": "öğretmen",
    "Lehrerin": "öğretmen",
    "Schüler": "öğrenci",
    "Prüfung": "sınav",
    "bestanden": "geçtim",
    "bestehen": "geçmek",
    "Beruf": "meslek",
    "Berufe": "meslekler",
    "Arzt": "doktor",
    "Ärztin": "doktor",
    "Polizist": "polis",
    "Altenpfleger": "yaşlı bakıcısı",
    "Job": "iş",
    "Arbeit": "iş",
    "arbeiten": "çalışmak",
    "gearbeitet": "çalıştım",
    "arbeitslos": "işsiz",
    "Büro": "ofis",
    "Firma": "şirket",
    "Firmen": "şirketler",
    "Chef": "patron",
    "Kollege": "meslektaş",
    "Kollegen": "meslektaşlar",
    "Mitarbeiter": "çalışan",
    "Überstunden": "mesai",
    "geht": "gidiyor",
    "Aufgabe": "görev",
    "Aufgaben": "görevler",
    "Rechnung": "fatura",
    "Rechnungen": "faturalar",
    "Vertrag": "sözleşme",
    "Verträge": "sözleşmeler",
    "Unterschrift": "imza",
    "unterschreiben": "imzalamak",
    "Bildung": "eğitim",
    "Bildungssystem": "eğitim sistemi",
    "Wort": "kelime",
    "Wörter": "kelimeler",

    # ─── House / apartment ───
    "Haus": "ev",
    "Wohnung": "daire",
    "Wohnungen": "daireler",
    "Zimmer": "oda",
    "Küche": "mutfak",
    "Bad": "banyo",
    "Schlafzimmer": "yatak odası",
    "Wohnzimmer": "oturma odası",
    "Badezimmer": "banyo",
    "Heizung": "ısıtma",
    "Miete": "kira",
    "Mieter": "kiracı",
    "Vermieter": "ev sahibi",
    "mieten": "kiralamak",
    "vermieten": "kiraya vermek",
    "vermietet": "kiraya verir",
    "Wohnung": "daire",
    "Büromaterial": "ofis malzemesi",
    "Schreibtisch": "çalışma masası",
    "Tisch": "masa",
    "Stuhl": "sandalye",
    "Stühle": "sandalyeler",
    "Spielplatz": "oyun alanı",
    "Bäume": "ağaçlar",
    "Baum": "ağaç",
    "Gebäude": "bina",
    "Gebäude": "binalar",
    "Häuser": "evler",

    # ─── Shopping / commerce ───
    "kaufen": "satın almak",
    "kaufe": "satın alıyorum",
    "gekauft": "satın aldım",
    "Einkaufsmöglichkeiten": "alışveriş imkanları",
    "Lebensmittel": "yiyecekler",
    "Supermarkt": "süpermarket",
    "Märkte": "pazarlar",
    "Angebot": "teklif",
    "Angebote": "teklifler",
    "Anzeige": "ilan",
    "Preis": "fiyat",
    "Preise": "fiyatlar",
    "Geld": "para",
    "Konto": "hesap",
    "Kreditkarte": "kredi kartı",
    "bar": "nakit",
    "überweisen": "havale etmek",
    "Überweisung": "havale",
    "Bezahlung": "ödeme",
    "bezahlen": "ödemek",
    "bezahlt": "ödedi",
    "Bezahlung": "ödeme",
    "Rechnung": "fatura",
    "Rechnungen": "faturalar",
    "Erstattung": "iade",
    "erstatten": "iade etmek",
    "Gebühr": "ücret",
    "Gebühren": "ücretler",
    "Kosten": "maliyet",
    "kosten": "tutmak",
    "kostenlos": "ücretsiz",
    "teuer": "pahalı",
    "billig": "ucuz",
    "günstig": "uygun",
    "teuer": "pahalı",
    "frisch": "taze",
    "Obst": "meyve",
    "Gemüse": "sebze",
    "Süßigkeiten": "şekerleme",
    "Kuchen": "pasta",
    "backen": "yapmak",
    "Ware": "mal",
    "gekaufte": "satın alınan",
    "wechseln": "değiştirmek",
    "versenden": "göndermek",
    "senden": "göndermek",
    "schicken": "göndermek",
    "Datei": "dosya",

    # ─── Health ───
    "krank": "hasta",
    "Krankheit": "hastalık",
    "Erkältung": "soğuk algınlığı",
    "Fieber": "ateş",
    "hohes": "yüksek",
    "Arzt": "doktor",
    "Ärzte": "doktorlar",
    "Krankenhaus": "hastane",
    "Krankenschreibung": "rapor",
    "krankgeschrieben": "rapor etti",
    "gesund": "sağlıklı",
    "Gesundheit": "sağlık",
    "Gesundheitssystem": "sağlık sistemi",
    "Medikament": "ilaç",
    "Tablette": "hap",
    "Behandlung": "tedavi",
    "behandeln": "tedavi etmek",
    "pflegen": "bakmak",
    "Pflege": "bakım",
    "Altenheim": "huzurevi",
    "Altenheime": "huzurevleri",
    "Altenpfleger": "yaşlı bakıcısı",

    # ─── Repairs / products ───
    "Fotoapparat": "fotoğraf makinesi",
    "Waschmaschine": "çamaşır makinesi",
    "Fernseher": "televizyon",
    "Maschine": "makine",
    "Maschinen": "makineler",
    "Gerät": "alet",
    "Geräte": "aletler",
    "Sportgeräte": "spor aletleri",
    "reparieren": "tamir etmek",
    "Reparatur": "tamir",
    "repariert": "tamir etti",
    "Handwerker": "usta",
    "Techniker": "teknisyen",
    "Werkzeug": "alet",
    "Werkzeuge": "aletler",
    "Anschluss": "bağlantı",
    "kontrollieren": "kontrol etmek",
    "überprüfen": "incelemek",
    "defekt": "bozuk",
    "kaputt": "bozuk",
    "funktioniert": "çalışıyor",
    "funktionieren": "çalışmak",
    "Garantie": "garanti",
    "Ersatz": "yedek",
    "ersetzen": "değiştirmek",

    # ─── Events / invitations ───
    "Party": "parti",
    "Feier": "kutlama",
    "feiern": "kutlamak",
    "Geburtstag": "doğum günü",
    "Hochzeit": "düğün",
    "Hochzeitstag": "evlenme yıldönümü",
    "Einladung": "davet",
    "einladen": "davet etmek",
    "lade": "davet ediyorum",
    "Teilnahme": "katılım",
    "teilnehmen": "katılmak",
    "mitbringen": "getirmek",
    "bringen": "getirmek",
    "bringe": "getiriyorum",
    "Restaurant": "restoran",
    "Königstraße": "Kral Caddesi",
    "Kebaphaus": "Kebap Evi",
    "Vertrag": "sözleşme",
    "kündigen": "feshetmek",
    "Kündigung": "fesih",
    "Kündigungsbestätigung": "fesih onayı",
    "Bestätigung": "onay",
    "bestätigen": "onaylamak",

    # ─── Help / please / thanks ───
    "Hilfe": "yardım",
    "helfen": "yardım etmek",
    "helfe": "yardım ediyorum",
    "geholfen": "yardım etti",
    "Gefallen": "iyilik",
    "Bitte": "rica",
    "bitte": "lütfen",
    "bitten": "istemek",
    "Dank": "teşekkür",
    "Danke": "teşekkürler",
    "Vielen": "Çok",
    "Dankeschön": "Teşekkür",
    "Bedanken": "Teşekkür",
    "bedanke": "teşekkür ederim",
    " danken": "teşekkür etmek",
    "Unterstützung": "destek",
    "unterstützen": "desteklemek",
    "unterstütze": "destekliyorum",
    "Mühe": "emeğiniz",
    "Bemühungen": "çabalarınız",
    "Verständnis": "anlayış",
    "freundlich": "kibar",
    "freundliche": "kibar",
    "Freund": "arkadaş",
    "Freunde": "arkadaşlar",
    "Freundschaft": "dostluk",
    "höflichst": "kibarca",

    # ─── Apology ───
    "Entschuldigung": "özür",
    "entschuldigen": "özür dilemek",
    "entschuldige": "özür dilerim",
    "Es": "tut",
    "leid": "üzgün",
    "tut": "yapıyor",
    "bedauern": "üzgün olmak",

    # ─── Problem / complaint ───
    "Problem": "sorun",
    "Probleme": "sorunlar",
    "probleme": "sorunlar",
    "beschweren": "şikayette bulunmak",
    "Beschwerde": "şikayet",
    "unzufrieden": "memnun değilim",
    "zufrieden": "memnun",
    "Sorge": "endişe",
    "Sorgen": "endişeler",
    "Lösung": "çözüm",
    "lösen": "çözmek",
    "pruefen": "incelemek",
    "prüfen": "incelemek",
    "Verbraucherzentrale": "Tüketici Merkezi",
    "Fall": "durum",
    "melden": "bildirmek",
    "gemeldet": "bildirildi",

    # ─── Knowledge / info ───
    "wissen": "bilmek",
    "weiß": "biliyorum",
    "wüsste": "bilirdim",
    "Wissen": "bilgi",
    "Information": "bilgi",
    "Informationen": "bilgiler",
    "ausführlichere": "daha detaylı",
    "Auskunft": "bilgi",
    "Unterlagen": "belgeler",
    "besorgen": "sağlamak",
    "besorgt": "sağladım",

    # ─── Misc common nouns ───
    "Bild": "resim",
    "Foto": "fotoğraf",
    "Fotos": "fotoğraflar",
    "Bildbeschreibung": "Resim Betimleme",
    "Atmosphäre": "atmosfer",
    "Hintergrund": "arka plan",
    "Leute": "insanlar",
    "Menschen": "insanlar",
    "Generation": "nesil",
    "Jugendliche": "gençler",
    "Leute": "insanlar",
    "Welt": "dünya",
    "Zukunft": "gelecek",
    "Vergangenheit": "geçmiş",
    "Kindheit": "çocukluk",
    "Leben": "hayat",
    "leben": "yaşamak",
    "lebe": "yaşıyorum",
    "Liebe": "sevgi",
    "liebe": "seviyorum",
    "mag": "seviyorum",
    "mögen": "sevmek",
    "interessant": "ilginç",
    "interessieren": "ilgilenmek",
    "interessiere": "ilgileniyorum",
    "Interesse": "ilgi",
    "Interessen": "ilgiler",
    "stolz": "gurur",
    "stolz": "gururlu",
    "Traumberuf": "hayalimdeki meslek",
    "Traum": "rüya",
    "wünsche": "diliyorum",
    "Wunsch": "dilek",
    "Wünsche": "dilekler",
    "Erfolg": "başarı",
    "Erfolge": "başarılar",
    "erfolgreich": "başarılı",
    "Glückwunsch": "tebrik",
    "Glückwünsche": "tebrikler",
    "Herzlichen": "İçten",
    "wert": "değer",
    "Wert": "değer",
    "Werte": "değerler",
    "Quelle": "kaynak",
    "Heimat": "vatan",
    "Heimatland": "vatan",
    "Land": "ülke",
    "Länder": "ülkeler",
    "Türkei": "Türkiye",
    "Deutschland": "Almanya",
    "Stuttgart": "Stuttgart",
    "Istanbul": "İstanbul",
    "Stadt": "şehir",
    "Straße": "sokak",
    "Haltstelle": "durak",
    "Haltestelle": "durak",
    "Park": "park",
    "Natur": "doğa",
    "Umwelt": "çevre",
    "Wetter": "hava",
    "Himmel": "gökyüzü",
    "Sonne": "güneş",
    "Wolken": "bulutlar",
    "Sommer": "yaz",
    "Winter": "kış",
    "Sommerkleidung": "yazlık kıyafetler",
    "Winterkleidung": "kışlık kıyafetler",
    "Kleidung": "kıyafet",
    "trage": "giyiyorum",
    "tragen": "giymek",
    "gucken": "bakmak",
    "sehe": "görüyorum",
    "sehen": "görmek",
    "sehe": "görüyorum",
    "aussehen": "görünmek",
    "seht": "görüyorsunuz",
    "aus": "görünüyorsunuz",
    "glücklich": "mutlu",
    "zufrieden": "memnun",
    "traurig": "üzgün",
    "müde": "yorgun",
    "gestresst": "stresli",
    "ruhig": "sakin",
    "fröhlich": "neşeli",
    "freundlich": "dostane",
    "wichtig": "önemli",
    "Wichtigkeit": "önem",
    "wichtige": "önemli",
    "wichtiger": "önemli",
    "schlecht": "kötü",
    "schlechter": "kötüleşen",
    "besser": "daha iyi",
    "beste": "en iyi",
    "Beste": "En iyi",
    "schwer": "zor",
    "schwierig": "zor",
    "leicht": "kolay",
    "einfach": "basit",
    "schöne": "güzel",
    "schönes": "güzel",
    "neu": "yeni",
    "alte": "eski",
    "alt": "yaşlı",
    "junge": "genç",
    "jung": "genç",
    "Junge": "genç",
    "ungefähr": "yaklaşık",
    "mehrere": "birkaç",
    "mehr": "daha fazla",
    "weniger": "daha az",
    "viele": "çok",
    "wenige": "az",
    "alle": "tüm",
    "jeden": "her",
    "jede": "her",
    "jedes": "her",
    "manche": "bazı",
    "manchmal": "bazen",
    "oft": "sık sık",
    "selten": "nadiren",
    "immer": "her zaman",
    "nie": "asla",
    "zusammen": "birlikte",
    "gemeinsam": "birlikte",
    "allein": "tek başına",
    "selbst": "kendim",
    "sich": "kendini",
    "mich": "beni",
    "dich": "seni",
    "uns": "bizi",
    "euch": "sizi",
    "unsere": "bizim",
    "meine": "benim",
    "deine": "senin",
    "ihre": "onun",
    "Ihre": "sizin",
    "Ihr": "sizin",
    "Unser": "bizim",
    "Euer": "sizin",
    "mein": "benim",
    "dein": "senin",
    "sein": "onun",
    "unser": "bizim",
    "euer": "sizin",
    "unseren": "bizim",
    "meinen": "benim",
    "ihren": "onların",

    # ─── Negation / question words ───
    "nicht": "değil",
    "kein": "hiç",
    "keine": "hiçbir",
    "keinen": "hiçbir",
    "keinem": "hiçbir",
    "Was": "Ne",
    "Wer": "Kim",
    "Wo": "Nerede",
    "Wann": "Ne zaman",
    "Wie": "Nasıl",
    "Warum": "Neden",
    "Wohin": "Nereye",
    "Woher": "Nereden",
    "Welche": "Hangi",
    "Welcher": "Hangi",
    "Welches": "Hangi",
    "Wessen": "Kimin",
    "niemanden": "kimseyi",
    "Niemand": "Kimse",
    "niemand": "kimse",
    "etwas": "bir şey",
    "Etwas": "Bir şey",
    "alles": "her şey",
    "nichts": "hiçbir şey",
    "Nichts": "Hiçbir şey",

    # ─── Verbs (more) ───
    "machen": "yapmak",
    "mache": "yapıyorum",
    "machst": "yapıyorsun",
    "macht": "yapıyor",
    "gemacht": "yaptım",
    "tun": "yapmak",
    "gehen": "gitmek",
    "gehe": "gidiyorum",
    "geht": "gidiyor",
    "gegangen": "gittim",
    "kommen": "gelmek",
    "komme": "geliyorum",
    "kommt": "geliyor",
    "gekommen": "geldim",
    "wollen": "istemek",
    "möchten": "istiyor",
    "dürfen": "izin",
    "müssen": "zorunda",
    "sollen": "gerekli",
    "können": "edebilmek",
    "mögen": "sevmek",
    "spielen": "oynamak",
    "spiele": "oynuyorum",
    "gespielt": "oynadım",
    "besuchen": "ziyaret etmek",
    "besuche": "ziyaret ediyorum",
    "besucht": "ziyaret ediyor",
    "Besuch": "ziyaret",
    "suchen": "aramak",
    "suche": "arıyorum",
    "Suche": "arama",
    "finden": "bulmak",
    "finde": "buluyorum",
    "gefunden": "buldum",
    "nehmen": "almak",
    "nehme": "alıyorum",
    "genommen": "aldım",
    "geben": "vermek",
    "gebe": "veriyorum",
    "gibt": "var",
    "gegeben": "verdim",
    "halten": "tutmak",
    "hält": "tutar",
    "gehalten": "tuttum",
    "denken": "düşünmek",
    "denke": "düşünüyorum",
    "gedacht": "düşündüm",
    "glauben": "inanmak",
    "glaube": "inanıyorum",
    "geglauft": "inandım",
    "versuchen": "denemek",
    "versuche": "deniyorum",
    "erinnern": "hatırlatmak",
    "erinnert": "hatırlatıyor",
    "erinnerte": "hatırlattı",
    "Erinnerung": "hatıra",
    "verbringen": "geçirmek",
    "verbringe": "geçiriyorum",
    "verbringt": "geçirir",
    "verbracht": "geçirdim",
    "interessieren": "ilgilenmek",
    "kennen": "tanımak",
    "kenne": "tanıyorum",
    "gekannt": "tanıdım",
    "wissen": "bilmek",
    "lernen": "öğrenmek",
    "lerne": "öğreniyorum",
    "gelernt": "öğrendim",
    "lehren": "öğretmek",
    "unterrichten": "ders vermek",
    "zeigt": "gösteriyor",
    "zeigen": "göstermek",
    "gezeigt": "gösterdim",
    "zeit": "zaman",
    "Zeit": "zaman",
    "Zeiten": "zamanlar",
    "pünktlich": "zamanında",
    "früher": "eskiden",
    "früh": "erken",
    "spät": "geç",
    "dauern": "sürmek",
    "dauert": "sürüyor",
    "dauerte": "sürdü",
    "Dauer": "süre",
    "beginnen": "başlamak",
    "beginnt": "başlıyor",
    "begann": "başladı",
    "anfangen": "başlamak",
    "fange": "başlıyorum",
    "fängt": "başlıyor",
    "angefangen": "başladım",
    "stattfinden": "olmak",
    "statt": "yerine",
    "findet": "oluyor",
    "fand": "oldu",
    "stattgefunden": "oldu",

    # ─── Directions / places ───
    "hier": "burada",
    "Hier": "Burada",
    "da": "orada",
    "dort": "orada",
    "oben": "yukarıda",
    "unten": "aşağıda",
    "links": "sol",
    "rechts": "sağ",
    "vorne": "öne",
    "hinten": "arkada",
    "wohnen": "yaşamak",
    "wohne": "yaşıyorum",
    "wohnt": "yaşıyor",
    "Wohnort": "yaşam yeri",
    "ziehen": "taşınmak",
    "gezogen": "taşındım",
    "umziehen": "taşınmak",
    "umgezogen": "taşındım",

    # ─── Movement / travel ───
    "fahren": "sürmek",
    "fahre": "sürüyorum",
    "Fahrrad": "bisiklet",
    "Radfahren": "bisiklet sürmek",
    "Fahrradfahren": "bisiklet sürmek",
    "Rad": "tekerlek",
    "wander": "yürüyüş",
    "wandern": "yürüyüşe çıkmak",
    "Wanderung": "yürüyüş",
    "Laufgruppe": "koşu grubu",
    "laufen": "koşmak",
    "Reise": "seyahat",
    "reisen": "seyahat etmek",
    " verreisen": "yolculuğa çıkmak",
    "Verreist": "yolculuktayım",
    "Urlaub": "tatil",
    "urlaub": "tatil",
    "Flug": "uçuş",
    "fliegen": "uçmak",
    "Zug": "tren",
    "Bahn": "tren",
    "Bus": "otobüs",
    "Auto": "araba",
    "Autos": "arabalar",
    "Verkehr": "trafik",
    "Stau": "trafik sıkışıklığı",

    # ─── Communication / internet ───
    "Internet": "internet",
    "online": "çevrimiçi",
    "bestellen": "sipariş etmek",
    "bestellt": "sipariş ettim",
    "Bestellung": "sipariş",
    "Handy": "cep telefonu",
    "Telefon": "telefon",
    "telefonieren": "telefon etmek",
    "Mobilnummer": "cep numarası",
    "Nummer": "numara",
    "Adresse": "adres",
    "E-Mail-Adresse": "e-posta adresi",
    "Computer": "bilgisayar",
    "Computerkurs": "bilgisayar kursu",
    "Fernseher": "televizyon",
    "TV": "TV",
    "Twitter": "Twitter",
    "Facebook": "Facebook",
    "Skype": "Skype",
    "Sozial": "Sosyal",
    "Soziales": "Sosyal",
    "Netzwerk": "ağ",

    # ─── Numbers ───
    "eins": "bir",
    "zwei": "iki",
    "drei": "üç",
    "vier": "dört",
    "fünf": "beş",
    "sechs": "altı",
    "sieben": "yedi",
    "acht": "sekiz",
    "neun": "dokuz",
    "zehn": "on",
    "elf": "on bir",
    "zwölf": "on iki",
    "dreizehn": "on üç",
    "vierzehn": "on dört",
    "fünfzehn": "on beş",
    "sechzehn": "on altı",
    "siebzehn": "on yedi",
    "achtzehn": "on sekiz",
    "neunzehn": "on dokuz",
    "zwanzig": "yirmi",
    "dreißig": "otuz",
    "vierzig": "kırk",
    "fünfzig": "elli",
    "zweitausend": "ikibin",
    "einhundert": "yüz",
    "zwanzigste": "yirminci",

    # ─── Misc / leftover ───
    "Müll": "çöp",
    "Mülltrennung": "çöp ayrımı",
    "Müllsystem": "çöp sistemi",
    "Recycling": "geri dönüşüm",
    "Umwelt": "çevre",
    "Umweltschutz": "çevre koruma",
    "schützen": "korumak",
    "schützt": "korur",
    "Tiere": "hayvanlar",
    "Tier": "hayvan",
    "Hund": "köpek",
    "Katze": "kedi",
    "Pferd": "at",
    "Vogel": "kuş",
    "Fisch": "balık",
    "Haustier": "evcil hayvan",
    "Sport": "spor",
    "Sportarten": "spor türleri",
    "Sportmöglichkeit": "spor imkanı",
    "Sportmöglichkeiten": "spor imkanları",
    "Sportstudio": "spor salonu",
    "Fitness-Studio": "spor salonu",
    "Fußball": "futbol",
    "Tischtennis": "masa tenisi",
    "Tennis": "tenis",
    "Gitarre": "gitar",
    "Musik": "müzik",
    "Lied": "şarkı",
    "Sänger": "şarkıcı",
    "Kino": "sinema",
    "Film": "film",
    "Filme": "filmler",
    "Buch": "kitap",
    "Bücher": "kitaplar",
    "Bücher": "kitaplar",
    "Bibliothek": "kütüphane",
    "Kochbuch": "yemek kitabı",
    "Kochbücher": "yemek kitapları",
    "kochen": "yemek yapmak",
    "Koche": "yemek yapıyorum",
    "gekoche": "yaptığım yemek",
    "Essen": "yemek",
    "essen": "yemek yemek",
    "esse": "yerim",
    "Trinken": "içmek",
    "trinke": "içiyorum",
    "Getränk": "içecek",
    "Getränke": "içecekler",
    "Spiel": "oyun",
    "Spiele": "oyunlar",
    "spiele": "oynuyorum",
    "Spielen": "Oynamak",
    "Flohmarkt": "bitpazarı",
    "Picknick": "piknik",
    "Freizeit": "boş zaman",
    "Freizeitaktivität": "boş zaman etkinliği",
    "Hobby": "hobi",
    "Hobbys": "hobiler",
    "Freizeitgestaltung": "boş zaman değerlendirme",
    "Treff": "buluşma",
    "treffen": "buluşmak",
    "treffe": "buluşuyorum",
    "getroffen": "buluştuk",
    "Treffpunkt": "buluşma noktası",
    "Verabredung": "randevu",
    "verabreden": "randevulaşmak",
    "Zimmer": "oda",
    "Familien": "aileler",
    "Geschenk": "hediye",
    "Geschenke": "hediyeler",
    "schenken": "hediye etmek",
    "Schenke": "hediye ediyorum",
    "Uhr": "saat",
    "Küche": "mutfak",
    "Debatte": "tartışma",
    "Diskussion": "tartışma",
    "diskutieren": "tartışmak",
    "Corona": "Corona",
    "Pandemie": "pandemi",
    "Maske": "maske",
    "Masken": "maskeler",
    "Krankheit": "hastalık",
    "Krankheiten": "hastalıklar",
    "Rassismus": "ırkçılık",
    "Technologie": "teknoloji",
    "technologisch": "teknolojik",
    "technologische": "teknolojik",
    "Technologien": "teknolojiler",
    "Ernährung": "beslenme",
    "gesunde": "sağlıklı",
    "gesunden": "sağlıklı",
    "gesundes": "sağlıklı",
    "Schutz": "koruma",
    "schützen": "korumak",
    "schutz": "koruma",
    "Tierschutz": "hayvan koruma",
    "Umweltschutz": "çevre koruma",

    # ─── Hobbies continued ───
    "Bücher": "kitaplar",
    "lesen": "okumak",
    "Lese": "okuyorum",
    "liest": "okuyor",
    "gelesen": "okudum",
    "Lesen": "okumak",
    "Schreiben": "yazı",
    "schreiben": "yazmak",
    "schreibe": "yazıyorum",
    "geschrieben": "yazdım",
    "Schreiber": "yazıcı",
    "Sprache": "dil",
    "Sprachen": "diller",
    "Fremdsprache": "yabancı dil",
    "Muttersprache": "ana dil",
    "Wortschatz": "kelime hazinesi",
    "Vokabel": "kelime",
    "Vokabeln": "kelimeler",
    "Grammatik": "gramer",
    "Aussprache": "telaffuz",
    "Bedeutung": "anlam",
    "bedeutet": "anlamına gelir",
    "heißen": "adı",
    "heißt": "adı",
    "Name": "isim",
    "Namen": "isimler",
    "namens": "adlı",

    # ─── Letter writing / formal phrases ───
    "Angelegenheit": "konu",
    "Angelegenheiten": "konular",
    "Angelegenheit": "iş",
    "Angelegenheiten": "işler",
    "Auftrag": "emir",
    "Bezug": "ilişkin",
    "bezüglich": "hakkında",
    "Anfrage": "talep",
    "anfragen": "talep etmek",
    "Termin": "randevu",
    "Termine": "randevular",
    "vereinbaren": "ayarlamak",
    "vereinbart": "ayrıldı",
    "absagen": "iptal etmek",
    "abgesagt": "iptal edildi",
    "verschieben": "ertelemek",
    "verschoben": "ertelendi",
    "stattfinden": "gerçekleşmek",
    "stattfand": "gerçekleşti",
    "bestätigen": "onaylamak",
    "bestätigt": "onaylar",
    "Bestätigung": "onay",
    "unterschreiben": "imzalamak",
    "Unterschrift": "imza",
    "Schreiben": "yazışma",
    "schreiben": "yazmak",
    "Unterricht": "ders",
    "unterrichten": "ders vermek",
    "Unterricht": "eğitim",
    "Prüfung": "sınav",
    "Prüfungen": "sınavlar",
    "bestehen": "geçmek",
    "bestanden": "geçtim",
    "bestehe": "geçiyorum",
    "durchfallen": "kalmak",
    "durchgefallen": "kaldım",
    "Note": "not",
    "Noten": "notlar",
    "Zeugnis": "karné",
    "Schuljahr": "okul yılı",
    "Schuljahre": "okul yılları",
    "Lehrer": "öğretmen",
    "Lehrerin": "öğretmen",
    "Lehrbuch": "ders kitabı",
    "Bücher": "kitaplar",
    "Aufgabe": "görev",
    "Aufgaben": "görevler",
    "Hausaufgaben": "ev ödevleri",
    "erledigen": "halletmek",
    "erledige": "hallediyorum",
    "erledigt": "halleder",
    "machen": "yapmak",
    "getan": "yaptım",
    "gemacht": "yaptım",

    # ─── Verbs continued ───
    "anbieten": "önermek",
    "biete": "öneriyorum",
    "bietet": "öneriyor",
    "geboten": "önerdim",
    "Angebot": "teklif",
    "Vorschlag": "öneri",
    "Vorschläge": "öneriler",
    "vorschlagen": "önermek",
    "schlage": "öneriyorum",
    "schlägt": "öneriyor",
    "vorgeschlagen": "önerdim",
    "meinen": "düşünmek",
    "meine": "düşünüyorum",
    "meinst": "düşünüyorsun",
    "meint": "düşünüyor",
    "Meinung": "görüş",
    "Meinungen": "görüşler",
    "Ansicht": "görüş",
    "Ansichten": "görüşler",
    "Standpunkt": "duruş",
    "Idee": "fikir",
    "Ideen": "fikirler",
    "denken": "düşünmek",
    "gedacht": "düşündüm",
    "überlegen": "düşünmek",
    "überlege": "düşünüyorum",
    "überlegt": "düşündü",
    "überzeugt": "ikna olmuş",
    "überzeugen": "ikna etmek",
    "zustimmen": "katılmak",
    "stimme": "katılıyorum",
    "stimmt": "katılıyor",
    "dagegen": "karşı",
    "dafür": "lehinde",
    "widersprechen": "karşı çıkmak",
    "kritisieren": "eleştirmek",
    "loben": "övmek",
    "Lob": "övme",

    # ─── Adjectives / adverbs ───
    "toll": "harika",
    "super": "süper",
    "schön": "güzel",
    "schöne": "güzel",
    "schönes": "güzel",
    "schöner": "güzel",
    "hässlich": "çirkin",
    "groß": "büyük",
    "große": "büyük",
    "großer": "büyük",
    "großes": "büyük",
    "klein": "küçük",
    "kleine": "küçük",
    "kleines": "küçük",
    "kleiner": "küçük",
    "lang": "uzun",
    "lange": "uzun",
    "länger": "daha uzun",
    "kurz": "kısa",
    "kurze": "kısa",
    "kürzer": "daha kısa",
    "hoch": "yüksek",
    "hohe": "yüksek",
    "höher": "daha yüksek",
    "höchste": "en yüksek",
    "niedrig": "düşük",
    "tief": "derin",
    "breit": "geniş",
    "breite": "geniş",
    "eng": "dar",
    "dick": "kalın",
    "dünne": "ince",
    "dünn": "ince",
    "rund": "yuvarlak",
    "eckig": "köşeli",
    "weit": "uzak",
    "nah": "yakın",
    "nahe": "yakın",
    "nächste": "önümüzdeki",
    "nächsten": "önümüzdeki",
    "nächster": "önümüzdeki",
    "vorige": "önceki",
    "voriger": "önceki",
    "voriges": "önceki",
    "letzte": "son",
    "letzter": "son",
    "letztes": "son",
    "erste": "ilk",
    "erster": "ilk",
    "erstes": "ilk",
    "zweite": "ikinci",
    "dritte": "üçüncü",
    "vierte": "dördüncü",
    "fünfte": "beşinci",
    "neue": "yeni",
    "neuer": "yeni",
    "neues": "yeni",
    "alten": "eski",
    "altes": "eski",
    "alter": "eski",
    "alte": "eski",
    "junge": "genç",
    "jünger": "daha genç",
    "jüngste": "en genç",
    "stark": "güçlü",
    "starke": "güçlü",
    "stärker": "daha güçlü",
    "schwach": "zayıf",
    "schwache": "zayıf",
    "schwere": "ağır",
    "leichter": "daha kolay",
    "leichtes": "kolay",
    "schnell": "hızlı",
    "schnelle": "hızlı",
    "schneller": "daha hızlı",
    "langsam": "yavaş",
    "langsame": "yavaş",
    "wärmer": "daha sıcak",
    "warm": "sıcak",
    "warme": "sıcak",
    "kalt": "soğuk",
    "kalte": "soğuk",
    "kälter": "daha soğuk",
    "kühler": "daha serin",
    "kühl": "serin",
    "heiß": "sıcak",
    "Hitze": "sıcak",
    "Kälte": "soğuk",
    "nass": "ıslak",
    "trocken": "kuru",
    "sauber": "temiz",
    "schmutzig": "kirli",
    "voll": "dolu",
    "leer": "boş",
    "offen": "açık",
    "geschlossen": "kapalı",
    "teuer": "pahalı",
    "teuren": "pahalı",
    "billig": "ucuz",
    "günstig": "uygun",
    "kostenlos": "ücretsiz",
    "gratis": "bedava",
    "ähnlich": "benzer",
    "anders": "farklı",
    "verschieden": "çeşitli",
    "verschiedene": "çeşitli",
    "gleich": "aynı",
    "selbe": "aynı",
    "wichtig": "önemli",
    "wichtige": "önemli",
    "wichtiger": "daha önemli",
    "unwichtig": "önemsiz",
    "nötig": "gerekli",
    "notwendig": "zorunlu",
    "überflüssig": "gereksiz",
    "möglich": "mümkün",
    "mögliche": "mümkün",
    "unmöglich": "imkansız",
    "vielleicht": "belki",
    "wahrscheinlich": "muhtemelen",
    "sicher": "emin",
    "sichere": "emin",
    "unsicher": "emin değil",
    "klar": "açık",
    "deutlich": "belirgin",
    "offensichtlich": "açıkça",
    "natürlich": "doğal olarak",
    "normal": "normal",
    "seltsam": "tuhaf",
    "komisch": "tuhaf",
    "interessant": "ilginç",
    "interessante": "ilginç",
    "langweilig": "sıkıcı",
    "lustig": "komik",
    "traurig": "üzgün",
    "glücklich": "mutlu",
    "zufrieden": "memnun",
    "unzufrieden": "memnun değil",
    "wütend": "öfkeli",
    "ärgerlich": "kızgın",
    "ärger": "öfke",
    "Angst": "korku",
    "ängstlich": "korkak",
    "mutig": "cesur",
    "freundlich": "dostane",
    "unfreundlich": "dostane değil",
    "höflich": "kibar",
    "unhöflich": "kaba",
    "nett": "nazik",
    "liebenswürdig": "sevecen",
    "liebe": "sevgili",
    "Liebe": "sevgi",
    "hass": "nefret",
    "Hass": "nefret",
    "wunderbar": "harika",
    "schrecklich": "korkunç",
    "furchtbar": "berbat",
    "tolle": "harika",
    "schlechte": "kötü",
    "schlimm": "kötü",
    "schlimmer": "daha kötü",
    "böse": "kötü",
    "gute": "iyi",
    "Gute": "İyi",
    "besser": "daha iyi",
    "beste": "en iyi",
    "Beste": "en iyi",
    "schwer": "ağır",
    "schwere": "ağır",
    "leicht": "hafif",
    "leichte": "hafif",
    "einfach": "basit",
    "einfache": "basit",
    "schwierig": "zor",
    "schwierige": "zor",
    "kompliziert": "karmaşık",
    "komplexe": "karmaşık",

    # ─── More common verbs ───
    "beginnen": "başlamak",
    "beginnt": "başlıyor",
    "begann": "başladı",
    "begonnen": "başlamış",
    "aufhören": "bırakmak",
    "höre": "duyuyorum",
    "aufhören": "son vermek",
    "stoppen": "durdurmak",
    "Ende": "son",
    "enden": "bitmek",
    "endet": "biter",
    "beenden": "bitirmek",
    "beendet": "bitirdi",
    "fertig": "hazır",
    "Fertig": "Hazır",
    "machen": "yapmak",
    "getan": "yapmış",
    "gemacht": "yaptım",
    "schaffen": "başarmak",
    "schaffe": "başarıyorum",
    "geschafft": "başardım",
    "versuchen": "denemek",
    "versucht": "denedi",
    "schaffen": "yapabilmek",
    "klappen": "işe yaramak",
    "klappt": "çalışıyor",
    "geklappt": "oldu",
    "funktionieren": "çalışmak",
    "funktioniert": "çalışıyor",
    "funktioniert": "işliyor",

    # ─── Common phrases ───
    "bitte": "lütfen",
    "Bitte": "Lütfen",
    "danke": "teşekkürler",
    "Danke": "Teşekkürler",
    "Vielen": "Çok",
    "Dank": "Teşekkür",
    "Dankeschön": "Teşekkürler",
    "Entschuldigung": "Özür",
    "Entschuldigen": "Özür",
    "Verzeihung": "Afferiş",
    "kein": "hiçbir",
    "Problem": "Sorun",
    "Probleme": "Sorunlar",

    # ─── Specific words found in the JSON ───
    "Hochzeit": "Düğün",
    "Hochzeitstag": "Yıldönümü",
    "Feier": "Kutlama",
    "feiern": "Kutlamak",
    "Geburtstag": "Doğum günü",
    "Geburtstagfeier": "Doğum günü partisi",
    "Einladung": "Davet",
    "einladen": "Davet etmek",
    "lade": "Davet ediyorum",
    "Einladung zum Vorstellungsgespräch": "Mülakat daveti",
    "Teilnahme": "Katılım",
    "teilnehmen": "Katılmak",
    "Kuchen": "Pasta",
    "backen": "Pişirmek",
    "mitbringen": "Getirmek",
    "Mitbringen": "Getirmek",
    "Bringen": "Getirmek",
    "bringe": "Getiriyorum",
    "Gefallen": "İyilik",
    "gefallen": "Hoşuna gitmek",
    "gefällt": "Hoşuna gidiyor",
    "gefallen": "Beğenmek",
    "Gefällt": "Beğeniyor",
    "gefiel": "Beğendi",
    "gefallen": "Memnun etmek",
    " Überstunden": "Mesai",
    "Mache": "Yapıyorum",
    "mache": "yapıyorum",
    "Beschäftigt": "Meşgul",
    "beschäftigt": "Meşgul",
    "Reise": "Seyahat",
    "Reisen": "Seyahatler",
    "Termin": "Randevu",
    "Termine": "Randevular",
    "Wochenende": "Hafta sonu",
    "Wochenenden": "Hafta sonları",
    "Recht": "Hak",
    "Rechte": "Haklar",
    "Regel": "Kural",
    "Regeln": "Kurallar",
    "Regeln": "Kurallar",
    "Vermieter": "Ev sahibi",
    "Mieter": "Kiracı",
    "Chef": "Patron",
    "Chefin": "Patron",
    "Chef": "Patron",
    "Punkte": "Maddeler",
    "Punkt": "Madde",
    "Erledigen": "Halletmek",
    "Sorge": "Endişe",
    "Sorgen": "Endişeler",
    "Mach": "Yap",
    "Sorgen": "Endişeler",
    "Sorgen": "Endişelenme",
    "Beschwerde": "Şikayet",
    "beschweren": "Şikayette bulunmak",
    "Beschweren": "Şikayette bulunmak",
    "Unzufrieden": "Memnun değilim",
    "Zufrieden": "Memnun",
    "Fehler": "Hata",
    "Fehler": "Yanlış",
    "Mängel": "Eksiklik",
    "Mangel": "Eksiklik",
    "Mangel": "Yetersizlik",
    "Funktioniert": "Çalışıyor",
    "Plötzlich": "Aniden",
    "Defekt": "Bozuk",
    "Kaputt": "Bozuk",
    "Garantie": "Garanti",
    "Reparatur": "Tamir",
    "Reparieren": "Tamir etmek",
    "Repariert": "Tamir etti",
    "Handwerker": "Usta",
    "Techniker": "Teknisyen",
    "Werkzeug": "Alet",
    "Werkzeuge": "Aletler",
    "Gerät": "Alet",
    "Geräte": "Aletler",
    "Anschluss": "Bağlantı",
    "Kontrollieren": "Kontrol etmek",
    "Überprüfen": "İncelemek",
    "Kontrolle": "Kontrol",
    "Untersuchung": "İnceleme",
    "Fotoapparat": "Fotoğraf makinesi",
    "Fernseher": "Televizyon",
    "Waschmaschine": "Çamaşır makinesi",
    "Maschine": "Makine",
    "Maschinen": "Makineler",
    "Ersatz": "Yedek",
    "Ersetzen": "Değiştirmek",
    "Wechseln": "Değiştirmek",
    "Gewechselt": "Değiştirildi",
    "Wechseln": "Değiştirmek",
    "Schicken": "Göndermek",
    "Schicke": "Gönderiyorum",
    "Geschickt": "Gönderdi",
    "Senden": "Göndermek",
    "Sende": "Gönderiyorum",
    "Gesendet": "Gönderildi",
    "Versenden": "Göndermek",
    "Versendet": "Gönderildi",
    "Versand": "Gönderim",
    "Lieferung": "Teslimat",
    "Liefern": "Teslim etmek",
    "Geliefert": "Teslim edildi",
    "Ware": "Mal",
    "Waren": "Mallar",
    "Gekaufte": "Satın alınan",
    "Gekauft": "Satın aldım",
    "Verbraucherzentrale": "Tüketici Merkezi",
    "Fall": "Durum",
    "Fälle": "Durumlar",
    "Melden": "Bildirmek",
    "Gemeldet": "Bildirildi",
    "Anzeige": "İlan",
    "Anzeigen": "İlanlar",
    "Zeitung": "Gazete",
    "Tageszeitung": "Günlük gazete",
    "Zeitungen": "Gazeteler",
    "Gelesen": "Okudum",
    "Lesen": "Okumak",
    "Lese": "Okuyorum",
    "liest": "okuyor",
    "Bücher": "Kitaplar",
    "Buch": "Kitap",
    "Bücher": "Kitaplar",
    "Bestellt": "Sipariş ettim",
    "Bestellen": "Sipariş etmek",
    "Bestellung": "Sipariş",
    "Bestellungen": "Siparişler",
    "Online": "Çevrimiçi",
    "Internet": "İnternet",
    "Im": "İçinde",
    "Überweisen": "Havale etmek",
    "Überweisung": "Havale",
    "Konto": "Hesap",
    "Kreditkarte": "Kredi kartı",
    "Bar": "Nakit",
    "Geschäft": "Mağaza",
    "Geschäfte": "Mağazalar",
    "Geschäft": "Dükkan",
    "Firma": "Şirket",
    "Firmen": "Şirketler",
    "Bank": "Banka",
    "Sparkasse": "Tasarruf bankası",
    "IBAN": "IBAN",
    "Gebühr": "Ücret",
    "Gebühren": "Ücretler",
    "Bezahlung": "Ödeme",
    "Bezahlen": "Ödemek",
    "Bezahlt": "Ödedi",
    "Kosten": "Maliyet",
    "Kosten": "Tutar",
    "Kostet": "Tutar",
    "Erstattung": "İade",
    "Erstatten": "İade etmek",
    "Erstattet": "İade etti",
    "Bezüglich": "Hakkında",
    "Preis": "Fiyat",
    "Preise": "Fiyatlar",
    "Preisen": "Fiyatlara",
    "Stunde": "Saat",
    "Stunden": "Saatler",
    "Pro": "Başına",
    "Teuer": "Pahalı",
    "Billig": "Ucuz",
    "Günstig": "Uygun",
    "Frisch": "Taze",
    "Frische": "Taze",
    "Obst": "Meyve",
    "Gemüse": "Sebze",
    "Märkte": "Pazarlar",
    "Markt": "Pazar",
    "Supermarkt": "Süpermarket",
    "Lebensmittel": "Yiyecekler",
    "Einkaufsmöglichkeiten": "Alışveriş imkanları",
    "Einkauf": "Alışveriş",
    "Einkaufen": "Alışveriş yapmak",
    "Kaufe": "Satın alıyorum",
    "Kauf": "Satın alma",
    "Angebot": "Teklif",
    "Angebote": "Teklifler",
    "Angebote": "Teklifler",
    "Angebot": "Teklif",
    "Besorgt": "Sağladım",
    "Besorgen": "Sağlamak",
    "Besorgungen": "Alışverişler",
    "Tages": "Günlük",
    "Bedürfnisse": "İhtiyaçlar",
    "Bedürfnis": "İhtiyaç",
    "Täglichen": "Günlük",
    "Alles": "Her şey",
    "Etwas": "Bir şey",
    "Nichts": "Hiçbir şey",
    "Jemand": "Biri",
    "Jemanden": "Birini",
    "Niemand": "Kimse",
    "Niemanden": "Kimseyi",
    "Man": "Biri",
    "Alle": "Tüm",
    "Alle": "Herkes",
    "Viele": "Çok",
    "Vielen": "Çok",
    "Wenige": "Az",
    "Wenig": "Az",
    "Mehr": "Daha fazla",
    "Mehrere": "Birkaç",
    "Weniger": "Daha az",
    "Meistens": "Çoğunlukla",
    "Meist": "Çoğunlukla",
    "Meistens": "Genellikle",
    "Meist": "Çoğu",
    "Andere": "Diğer",
    "Anderen": "Diğer",
    "Anderem": "Diğer",
    "Anderer": "Diğer",
    "Solche": "Böyle",
    "Solcher": "Böyle",
    "Dieses": "Bu",
    "Dieser": "Bu",
    "Diese": "Bu",
    "Dies": "Bu",
    "Jener": "Şu",
    "Jene": "Şu",
    "Jedes": "Her",
    "Jede": "Her",
    "Jeden": "Her",
    "Jedem": "Her",
    "Manche": "Bazı",
    "Manchen": "Bazı",
    "Manchem": "Bazı",
    "Mancher": "Bazı",

    # ─── Places continued ───
    "Schule": "Okul",
    "Schulen": "Okullar",
    "Kindergarten": "Anaokulu",
    "Kindergärten": "Anaokulları",
    "Gymnasium": "Lise",
    "Universität": "Üniversite",
    "Universitäten": "Üniversiteler",
    "Hochschule": "Yüksekokul",
    "Studium": "Üniversite eğitimi",
    "Studiert": "Okudu",
    "Studieren": "Okumak",
    "Studiere": "Okuyorum",
    "Unterricht": "Ders",
    "Unterrichts": "Dersin",
    "Kurs": "Kurs",
    "Kurse": "Kurslar",
    "Kursen": "Kurslara",
    "Prüfung": "Sınav",
    "Prüfungen": "Sınavlar",
    "Bestanden": "Geçtim",
    "Bestehen": "Geçmek",
    "Bestehe": "Geçiyorum",
    "Durchgefallen": "Kaldım",
    "Durchfallen": "Kalmak",
    "Note": "Not",
    "Noten": "Notlar",
    "Zeugnis": "Karné",
    "Zeugnisse": "Karneler",
    "Schuljahr": "Okul yılı",
    "Lehrer": "Öğretmen",
    "Lehrerin": "Öğretmen",
    "Lehrbücher": "Ders kitapları",
    "Lehrbuch": "Ders kitabı",
    "Aufgabe": "Görev",
    "Aufgaben": "Görevler",
    "Hausaufgaben": "Ev ödevleri",
    "Erledigen": "Halletmek",
    "Erledigt": "Halleder",
    "Erledige": "Hallediyorum",
    "Erledigt": "Halledildi",
    "Punkt": "Madde",
    "Punkte": "Maddeler",
    "Punkten": "Maddeleri",
    "Regel": "Kural",
    "Regeln": "Kurallar",
    "Recht": "Hak",
    "Rechte": "Haklar",
    "Rechten": "Hakları",
    "Mieter": "Kiracı",
    "Mieter": "Kiracılar",
    "Vermieter": "Ev sahibi",
    "Vermieter": "Ev sahipleri",
    "Wohnung": "Daire",
    "Wohnungen": "Daireler",
    "Haus": "Ev",
    "Häuser": "Evler",
    "Zimmer": "Oda",
    "Zimmern": "Odalar",
    "Küche": "Mutfak",
    "Küchen": "Mutfaklar",
    "Bad": "Banyo",
    "Badezimmer": "Banyo",
    "Bäder": "Banyolar",
    "Schlafzimmer": "Yatak odası",
    "Wohnzimmer": "Oturma odası",
    "Heizung": "Isıtma",
    "Heizungen": "Isıtmalar",
    "Miete": "Kira",
    "Mieten": "Kiralamak",
    "Gemietet": "Kiraladı",
    "Vermietet": "Kiraya verir",
    "Vermietung": "Kiralama",
    "Stadt": "Şehir",
    "Städte": "Şehirler",
    "Land": "Ülke",
    "Länder": "Ülkeler",
    "Heimat": "Vatan",
    "Heimatland": "Vatan",
    "Heimatstadt": "Memleket",
    "Heimatland": "Anavatan",
    "Deutschland": "Almanya",
    "Türkei": "Türkiye",
    "Stuttgart": "Stuttgart",
    "Istanbul": "İstanbul",
    "Königstraße": "Kral Caddesi",
    "Straße": "Sokak",
    "Straßen": "Sokaklar",
    "Restaurant": "Restoran",
    "Restaurants": "Restoranlar",
    "Kebaphaus": "Kebap Evi",
    "Spielplatz": "Oyun alanı",
    "Spielplätze": "Oyun alanları",
    "Park": "Park",
    "Parks": "Parklar",
    "Garten": "Bahçe",
    "Gärten": "Bahçeler",
    "Büro": "Ofis",
    "Büros": "Ofisler",
    "Arbeitsplatz": "İş yeri",
    "Firma": "Şirket",
    "Firmen": "Şirketler",
    "Geschäft": "Mağaza",
    "Geschäfte": "Mağazalar",
    "Werkstatt": "Atölye",
    "Werkstätten": "Atölyeler",
    "Krankenhaus": "Hastane",
    "Krankenhäuser": "Hastaneler",
    "Arzt": "Doktor",
    "Ärzte": "Doktorlar",
    "Ärztin": "Doktor",
    "Arztpraxis": "Doktor muayenehanesi",
    "Praxis": "Muayenehane",
    "Klinik": "Klinik",
    "Kliniken": "Klinikler",
    "Apotheke": "Eczane",
    "Apotheken": "Eczaneler",
    "Schule": "Okul",
    "Schulen": "Okullar",
    "Gericht": "Mahkeme",
    "Behörde": "Resmi daire",
    "Behörden": "Resmi daireler",
    "Amt": "Daire",
    "Ämter": "Daireler",
    "Polizei": "Polis",
    "Polizist": "Polis",
    "Polizisten": "Polisler",
    "Feuerwehr": "İtfaiye",
    "Krankenwagen": "Ambulans",
    "Taxi": "Taksi",
    "Bushaltestelle": "Otobüs durağı",
    "Haltestelle": "Durak",
    "Haltestellen": "Duraklar",
    "Bahnhof": "Tren istasyonu",
    "Bahnhöfe": "Tren istasyonları",
    "Flughafen": "Havaalanı",
    "Flughäfen": "Havaalanları",

    # ─── Sentence connectors / phrases ───
    "Zuerst": "Öncelikle",
    "Zunächst": "Öncelikle",
    "Danach": "Sonra",
    "Dann": "Sonra",
    "Später": "Sonra",
    "Schließlich": "Sonuç olarak",
    "Endlich": "Sonunda",
    "Am": "de",
    "Ende": "Son",
    "Am": "de",
    "Anfang": "Başlangıç",
    "Am": "de",
    "Anfang": "Başlangıçta",
    "Inzwischen": "Bu arada",
    "Mittlerweile": "Bu arada",
    "Währenddessen": "Bu sırada",
    "Gleichzeitig": "Aynı anda",
    "Sofort": "Hemen",
    "Sofort": "Derhal",
    "Augenblicklich": "Şu an",
    "Momentan": "Şu anda",
    "Heutzutage": "Günümüzde",
    "Heute": "Bugün",
    "Morgen": "Yarın",
    "Gestern": "Dün",
    "Heutige": "Bugünkü",
    "Früher": "Eskiden",
    "Damals": "O zamanlar",
    "Neulich": "Son zamanlarda",
    "Kürzlich": "Yakın zamanda",
    "Vor": "Önce",
    "Vorher": "Önceden",
    "Nachher": "Sonradan",
    "Bald": "Yakında",
    "Baldige": "Yakın",
    "Baldigen": "Yakın",
    "Eilig": "Acil",
    "Eilige": "Acil",
    "Schnell": "Hızlı",
    "Schnelle": "Hızlı",
    "Schnellstmöglich": "En hızlı şekilde",
    "Schnellstmögliche": "En hızlı",
    "So": "Böylece",
    "Schnell": "Hızlı",
    "Wie": "gibi",
    "Möglich": "Mümkün",
    "Möglichst": "Mümkün olduğunca",
    "Möglich": "Olabildiğince",
    "Schnell": "Hızlı",
    "Schnell": "Çabuk",

    # ─── More pronouns / determiners ───
    "Ich": "Ben",
    "Du": "Sen",
    "Er": "O",
    "Sie": "O",
    "Es": "O",
    "Wir": "Biz",
    "Ihr": "Siz",
    "Sie": "Siz",
    "Sie": "Onlar",
    "Mein": "Benim",
    "Dein": "Senin",
    "Sein": "Onun",
    "Ihr": "Onun",
    "Unser": "Bizim",
    "Euer": "Sizin",
    "Ihr": "Sizin",
    "Meine": "Benim",
    "Deine": "Senin",
    "Seine": "Onun",
    "Ihre": "Onun",
    "Unsere": "Bizim",
    "Eure": "Sizin",
    "Ihre": "Sizin",
    "Meinen": "Benim",
    "Deinen": "Senin",
    "Seinen": "Onun",
    "Ihren": "Onun",
    "Unseren": "Bizim",
    "Euren": "Sizin",
    "Ihren": "Sizin",
    "Meinem": "Benim",
    "Deinem": "Senin",
    "Seinem": "Onun",
    "Ihrem": "Onun",
    "Unserem": "Bizim",
    "Eurem": "Sizin",
    "Ihrem": "Sizin",
    "Meines": "Benim",
    "Deines": "Senin",
    "Seines": "Onun",
    "Ihres": "Onun",
    "Unsers": "Bizim",
    "Eures": "Sizin",
    "Ihres": "Sizin",
    "Mir": "Bana",
    "Dir": "Sana",
    "Ihm": "Ona",
    "Ihr": "Ona",
    "Uns": "Bize",
    "Euch": "Size",
    "Ihnen": "Onlara",
    "Mich": "Beni",
    "Dich": "Seni",
    "Ihn": "Onu",
    "Sie": "Onu",
    "Es": "Onu",
    "Uns": "Bizi",
    "Euch": "Sizi",
    "Sie": "Onları",

    # ─── Greetings / partings ───
    "Hallo": "Merhaba",
    "Hi": "Merhaba",
    "Guten": "İyi",
    "Morgen": "Sabah",
    "Guten": "İyi",
    "Tag": "Gün",
    "Guten": "İyi",
    "Abend": "Akşam",
    "Gute": "İyi",
    "Nacht": "Gece",
    "Tschüss": "Hoşça kal",
    "Auf": "Görüşmek",
    "Wiedersehen": "üzere",
    "Bis": "Kadar",
    "Bis": "Kadar",
    "bald": "yakında",
    "Bis": "Kadar",
    "später": "sonra",
    "Bis": "Kadar",
    "morgen": "yarın",

    # ─── Yes / no / please / thanks ───
    "Ja": "Evet",
    "Nein": "Hayır",
    "Jawohl": "Evet",
    "Natürlich": "Elbette",
    "Klar": "Tabii",
    "Selbstverständlich": "Kuşkusuz",
    "Bitte": "Lütfen",
    "Bitte": "Rica ederim",
    "Danke": "Teşekkürler",
    "Dankeschön": "Teşekkürler",
    "Vielen": "Çok",
    "Vielen": "Çok",
    "Dank": "Teşekkür",
    "Herzlichen": "İçten",
    "Dank": "Teşekkür",

    # ─── Adjectives continued ───
    "Schön": "Güzel",
    "Schöne": "Güzel",
    "Schöner": "Güzel",
    "Schönes": "Güzel",
    "Wunderschön": "Harika",
    "Hässlich": "Çirkin",
    "Hübsch": "Hoş",
    "Hübsche": "Hoş",
    "Süß": "Tatlı",
    "Süße": "Tatlı",
    "Lieb": "Tatlı",
    "Liebe": "Sevgi",
    "Nett": "Nazik",
    "Nette": "Nazik",
    "Freundlich": "Dostane",
    "Freundliche": "Dostane",
    "Unfreundlich": "Dostane değil",
    "Höflich": "Kibar",
    "Höfliche": "Kibar",
    "Unhöflich": "Kaba",
    "Grob": "Kaba",
    "Arrogant": "Kibirli",
    "Bescheiden": "Alçakgönüllü",
    "Stolz": "Gururlu",
    "Beschämt": "Utanmış",
    "Froh": "Mutlu",
    "Glücklich": "Mutlu",
    "Zufrieden": "Memnun",
    "Traurig": "Üzgün",
    "Traurige": "Üzgün",
    "Verletzt": " incinmiş",
    "Wütend": "Öfkeli",
    "Böse": "Kızgın",
    "Ärgerlich": "Kızgın",
    "Enttäuscht": "Hayal kırıklığına uğramış",
    "Begeistert": "Coşkulu",
    "Aufgeregt": "Heyecanlı",
    "Ruhig": "Sakin",
    "Ruhige": "Sakin",
    "Entspannt": "Rahatlamış",
    "Gestresst": "Stresli",
    "Müde": "Yorgun",
    "Erschöpft": "Bitkin",
    "Krank": "Hasta",
    "Gesund": "Sağlıklı",
    "Fit": "Formda",
    "Stark": "Güçlü",
    "Schwach": "Zayıf",
    "Dünn": "İnce",
    "Dick": "Kalın",
    "Groß": "Büyük",
    "Klein": "Küçük",
    "Große": "Büyük",
    "Kleine": "Küçük",
    "Großer": "Büyük",
    "Kleiner": "Küçük",
    "Großes": "Büyük",
    "Kleines": "Küçük",
    "Lang": "Uzun",
    "Kurz": "Kısa",
    "Lange": "Uzun",
    "Kurze": "Kısa",
    "Langer": "Uzun",
    "Kurzer": "Kısa",
    "Langen": "Uzun",
    "Kurzen": "Kısa",
    "Hoch": "Yüksek",
    "Niedrig": "Düşük",
    "Hohe": "Yüksek",
    "Niedrige": "Düşük",
    "Hoher": "Yüksek",
    "Niedriger": "Düşük",
    "Hohes": "Yüksek",
    "Niedriges": "Düşük",
    "Breit": "Geniş",
    "Eng": "Dar",
    "Breite": "Geniş",
    "Enge": "Dar",
    "Breiter": "Geniş",
    "Enge": "Dar",
    "Tief": "Derin",
    "Tiefe": "Derin",
    "Tiefer": "Derin",
    "Tiefes": "Derin",
    "Flach": "Sığ",
    "Flache": "Sığ",
    "Rund": "Yuvarlak",
    "Runde": "Yuvarlak",
    "Eckig": "Köşeli",
    "Eckige": "Köşeli",
    "Weich": "Yumuşak",
    "Weiche": "Yumuşak",
    "Hart": "Sert",
    "Harte": "Sert",
    "Glatt": "Pürüzsüz",
    "Glatte": "Pürüzsüz",
    "Rau": "Pürüzlü",
    "Raue": "Pürüzlü",
    "Heiß": "Sıcak",
    "Kalt": "Soğuk",
    "Warm": "Ilık",
    "Kühl": "Serin",
    "Heiße": "Sıcak",
    "Kalte": "Soğuk",
    "Warme": "Ilık",
    "Kühle": "Serin",
    "Trocken": "Kuru",
    "Nass": "Islak",
    "Feucht": "Nemli",
    "Trockene": "Kuru",
    "Nasse": "Islak",
    "Feuchte": "Nemli",
    "Sonnig": "Güneşli",
    "Regnerisch": "Yağmurlu",
    "Bewölkt": "Bulutlu",
    "Windig": "Rüzgarlı",
    "Schnee": "Kar",
    "Schneien": "Kar yağmak",
    "Regen": "Yağmur",
    "Regnen": "Yağmur yağmak",
    "Wind": "Rüzgar",
    "Wolke": "Bulut",
    "Wolken": "Bulutlar",
    "Sonne": "Güneş",
    "Sonnig": "Güneşli",
    "Himmel": "Gökyüzü",
    "Wetter": "Hava",
    "Wettervorhersage": "Hava tahmini",
    "Temperatur": "Sıcaklık",
    "Grad": "Derece",
    "Klima": "İklim",
    "Jahreszeit": "Mevsim",
    "Jahreszeiten": "Mevsimler",
    "Frühling": "İlkbahar",
    "Sommer": "Yaz",
    "Herbst": "Sonbahar",
    "Winter": "Kış",
    "Frühlings": "İlkbahar",
    "Sommer": "Yaz",
    "Herbst": "Sonbahar",
    "Winter": "Kış",
    "Sommerkleidung": "Yazlık kıyafet",
    "Winterkleidung": "Kışlık kıyafet",
    "Kleidung": "Kıyafet",
    "Kleider": "Elbiseler",
    "Anzug": "Takım elbise",
    "Anzüge": "Takım elbiseler",
    "Hose": "Pantolon",
    "Hosen": "Pantolonlar",
    "Hemd": "Gömlek",
    "Hemden": "Gömlekler",
    "Bluse": "Bluz",
    "Blusen": "Bluzlar",
    "Jacke": "Ceket",
    "Jacken": "Ceketler",
    "Mantel": "Palto",
    "Mäntel": "Paltolar",
    "Schuh": "Ayakkabı",
    "Schuhe": "Ayakkabılar",
    "Stiefel": "Çizme",
    "Stiefel": "Çizmeler",
    "Mütze": "Şapka",
    "Mützen": "Şapkalar",
    "Hut": "Şapka",
    "Hüte": "Şapkalar",
    "Schal": "Atkı",
    "Schals": "Atkılar",
    "Handschuhe": "Eldivenler",
    "Handschuh": "Eldiven",
    "Socke": "Çorap",
    "Socken": "Çoraplar",

    # ─── Misc from sentences ───
    "Stück": "Parça",
    "Stücke": "Parçalar",
    "Mal": "Kez",
    "Male": "Kezler",
    "Teil": "Bölüm",
    "Teile": "Bölümler",
    "Teil": "Kısım",
    "Teile": "Kısımlar",
    "Stelle": "Yer",
    "Stellen": "Yerler",
    "Stellen": "İş ilanları",
    "Stelle": "İş",
    "Arbeitsstelle": "İş yeri",
    "Arbeitsplätze": "İş yerleri",
    "Arbeitsplatz": "İş yeri",
    "Stelle": "Pozisyon",
    "Stellen": "Pozisyonlar",
    "Bewerbung": "Başvuru",
    "Bewerben": "Başvurmak",
    "Bewerber": "Başvuran",
    "Bewerber": "Aday",
    "Bewerberinnen": "Adaylar",
    "Bewerbung": "İş başvurusu",
    "Bewerbungen": "Başvurular",
    "Lebenslauf": "Özgeçmiş",
    "Lebensläufe": "Özgeçmişler",
    "Zeugnis": "Belge",
    "Zeugnisse": "Belgeler",
    "Zertifikat": "Sertifika",
    "Zertifikate": "Sertifikalar",
    "Diplom": "Diploma",
    "Diplome": "Diplomalar",
    "Abschluss": "Mezuniyet",
    "Abschlüsse": "Mezuniyetler",
    "Studium": "Eğitim",
    "Ausbildung": "Eğitim",
    "Ausbildungen": "Eğitimler",
    "Kurs": "Kurs",
    "Kurse": "Kurslar",
    "Schulung": "Eğitim",
    "Schulungen": "Eğitimler",
    "Seminar": "Seminer",
    "Seminare": "Seminerler",
    "Workshop": "Atölye",
    "Workshops": "Atölyeler",
    "Vortrag": "Konferans",
    "Vorträge": "Konferanslar",
    "Präsentation": "Sunum",
    "Präsentationen": "Sunumlar",
    "Referat": "Sunum",
    "Referate": "Sunumlar",
    "Hausarbeit": "Tez",
    "Hausarbeiten": "Tezler",
    "Projekt": "Proje",
    "Projekte": "Projeler",
    "Forschung": "Araştırma",
    "Forschen": "Araştırmak",
    "Forscher": "Araştırmacı",
    "Forscherin": "Araştırmacı",
    "Experiment": "Deney",
    "Experimente": "Deneyler",
    "Theorie": "Teori",
    "Theorien": "Teoriler",
    "Praxis": "Pratik",
    "Praktik": "Staj",
    "Praktika": "Stajlar",
    "Praktikum": "Staj",
    "Praktika": "Stajlar",
    "Praktikant": "Stajyer",
    "Praktikantin": "Stajyer",
    "Praktikanten": "Stajyerler",
    "Berufserfahrung": "İş deneyimi",
    "Erfahrung": "Deneyim",
    "Erfahrungen": "Deneyimler",
    "Erfahren": "Deneyimlemek",
    "Kenntnisse": "Bilgiler",
    "Kenntnis": "Bilgi",
    "Fähigkeit": "Yetenek",
    "Fähigkeiten": "Yetenekler",
    "Fähig": "Yetenekli",
    "Begabung": "Yetenek",
    "Begabungen": "Yetenekler",
    "Talent": "Yetenek",
    "Talente": "Yetenekler",
    "Interesse": "İlgi",
    "Interessen": "İlgiler",
    "Hobby": "Hobi",
    "Hobbys": "Hobiler",
    "Freizeit": "Boş zaman",
    "Freizeitbeschäftigung": "Boş zaman etkinliği",
    "Freizeitgestaltung": "Boş zaman değerlendirme",
    "Freizeitaktivität": "Boş zaman etkinliği",
    "Freizeitaktivitäten": "Boş zaman etkinlikleri",

    # ─── Body parts ───
    "Kopf": "Baş",
    "Köpfe": "Başlar",
    "Haar": "Saç",
    "Haare": "Saçlar",
    "Gesicht": "Yüz",
    "Gesichter": "Yüzler",
    "Auge": "Göz",
    "Augen": "Gözler",
    "Nase": "Burun",
    "Nasen": "Burunlar",
    "Mund": "Ağız",
    "Münder": "Ağızlar",
    "Ohr": "Kulak",
    "Ohren": "Kulaklar",
    "Zahn": "Diş",
    "Zähne": "Dişler",
    "Hals": "Boyun",
    "Hälse": "Boyunlar",
    "Hand": "El",
    "Hände": "Eller",
    "Finger": "Parmak",
    "Finger": "Parmaklar",
    "Arm": "Kol",
    "Arme": "Kollar",
    "Bein": "Bacak",
    "Beine": "Bacaklar",
    "Fuß": "Ayak",
    "Füße": "Ayaklar",
    "Bauch": "Karın",
    "Bauchs": "Karın",
    "Rücken": "Sırt",
    "Brust": "Göğüs",
    "Brüste": "Göğüsler",
    "Herz": "Kalp",
    "Herzen": "Kalpler",
    "Haut": "Deri",
    "Knochen": "Kemik",
    "Knochen": "Kemikler",
    "Muskeln": "Kaslar",
    "Muskel": "Kas",
    "Blut": "Kan",
    "Nerv": "Sinir",
    "Nerven": "Sinirler",
    "Gehirn": "Beyin",
    "Lunge": "Akciğer",
    "Lungen": "Akciğerler",
    "Magen": "Mide",
    "Mägen": "Mideler",
    "Leber": "Karaciğer",
    "Niere": "Böbrek",
    "Nieren": "Böbrekler",

    # ─── Food / drinks ───
    "Essen": "Yemek",
    "Brot": "Ekmek",
    "Brote": "Ekmekler",
    "Brötchen": "Çörek",
    "Brötchen": "Çörekler",
    "Käse": "Peynir",
    "Wurst": "Sosis",
    "Würste": "Sosisler",
    "Fleisch": "Et",
    "Fleisch": "Etler",
    "Fisch": "Balık",
    "Fische": "Balıklar",
    "Hähnchen": "Tavuk",
    "Hähnchen": "Tavuklar",
    "Ei": "Yumurta",
    "Eier": "Yumurtalar",
    "Milch": "Süt",
    "Butter": "Tereyağı",
    "Joghurt": "Yoğurt",
    "Käse": "Peynir",
    "Quark": "Lor",
    "Obst": "Meyve",
    "Äpfel": "Elmalar",
    "Apfel": "Elma",
    "Birne": "Armut",
    "Birnen": "Armutlar",
    "Banane": "Muz",
    "Bananen": "Muzlar",
    "Orange": "Portakal",
    "Orangen": "Portakallar",
    "Zitrone": "Limon",
    "Zitronen": "Limonlar",
    "Traube": "Üzüm",
    "Trauben": "Üzümler",
    "Erdbeere": "Çilek",
    "Erdbeeren": "Çilekler",
    "Tomate": "Domates",
    "Tomaten": "Domatesler",
    "Gurke": "Salatalık",
    "Gurken": "Salatalıklar",
    "Kartoffel": "Patates",
    "Kartoffeln": "Patatesler",
    "Zwiebel": "Soğan",
    "Zwiebeln": "Soğanlar",
    "Knoblauch": "Sarımsak",
    "Salat": "Salata",
    "Salate": "Salatalar",
    "Reis": "Pirinç",
    "Nudel": "Makarna",
    "Nudeln": "Makarnalar",
    "Pizza": "Pizza",
    "Pizzen": "Pizzalar",
    "Pasta": "Makarna",
    "Suppe": "Çorba",
    "Suppen": "Çorbalar",
    "Kuchen": "Pasta",
    "Kuchen": "Kek",
    "Torte": "Pasta",
    "Torten": "Pastalar",
    "Schokolade": "Çikolata",
    "Süßigkeiten": "Şekerleme",
    "Keks": "Kurabiye",
    "Kekse": "Kurabiyeler",
    "Eis": "Dondurma",
    "Eis": "Buz",
    "Wasser": "Su",
    "Saft": "Meyve suyu",
    "Säfte": "Meyve suları",
    "Kaffee": "Kahve",
    "Tee": "Çay",
    "Bier": "Bira",
    "Biere": "Biralar",
    "Wein": "Şarap",
    "Weine": "Şaraplar",
    "Milch": "Süt",
    "Getränk": "İçecek",
    "Getränke": "İçecekler",
    "Mineralwasser": "Maden suyu",
    "Limonade": "Limonata",
    "Cola": "Kola",
    "Wein": "Şarap",
    "Bier": "Bira",
    "Sekt": "Köpüklü şarap",
    "Champagner": "Şampanya",

    # ─── Animals ───
    "Tier": "Hayvan",
    "Tiere": "Hayvanlar",
    "Hund": "Köpek",
    "Hunde": "Köpekler",
    "Katze": "Kedi",
    "Katzen": "Kediler",
    "Maus": "Fare",
    "Mäuse": "Fareler",
    "Vogel": "Kuş",
    "Vögel": "Kuşlar",
    "Fisch": "Balık",
    "Fische": "Balıklar",
    "Pferd": "At",
    "Pferde": "Atlar",
    "Kuh": "İnek",
    "Kühe": "İnekler",
    "Schwein": "Domuz",
    "Schweine": "Domuzlar",
    "Schaf": "Koyun",
    "Schafe": "Koyunlar",
    "Ziege": "Keçi",
    "Ziegen": "Keçiler",
    "Huhn": "Tavuk",
    "Hühner": "Tavuklar",
    "Ente": "Ördek",
    "Enten": "Ördekler",
    "Gans": "Kaz",
    "Gänse": "Kazlar",
    "Kaninchen": "Tavşan",
    "Kaninchen": "Tavşanlar",
    "Hase": "Tavşan",
    "Hasen": "Tavşanlar",
    "Bär": "Ayı",
    "Bären": "Ayılar",
    "Löwe": "Aslan",
    "Löwen": "Aslanlar",
    "Tiger": "Kaplan",
    "Tiger": "Kaplanlar",
    "Elefant": "Fil",
    "Elefanten": "Filler",
    "Affe": "Maymun",
    "Affen": "Maymunlar",
    "Schlange": "Yılan",
    "Schlangen": "Yılanlar",
    "Frosch": "Kurbağa",
    "Frösche": "Kurbağalar",
    "Insekt": "Böcek",
    "Insekten": "Böcekler",
    "Biene": "Arı",
    "Bienen": "Arılar",
    "Fliege": "Sinek",
    "Fliegen": "Sinekler",
    "Mücke": "Sivrisinek",
    "Mücken": "Sivrisinekler",
    "Spinne": "Örümcek",
    "Spinnen": "Örümcekler",
    "Wurm": "Solucan",
    "Würmer": "Solucanlar",

    # ─── Plants / nature ───
    "Pflanze": "Bitki",
    "Pflanzen": "Bitkiler",
    "Baum": "Ağaç",
    "Bäume": "Ağaçlar",
    "Blume": "Çiçek",
    "Blumen": "Çiçekler",
    "Gras": "Çim",
    "Wald": "Orman",
    "Wälder": "Ormanlar",
    "Berg": "Dağ",
    "Berge": "Dağlar",
    "Hügel": "Tepe",
    "Hügel": "Tepeler",
    "Tal": "Vadi",
    "Täler": "Vadiler",
    "Fluss": "Nehir",
    "Flüsse": "Nehirler",
    "See": "Göl",
    "Seen": "Göller",
    "Meer": "Deniz",
    "Meere": "Denizler",
    "Ozean": "Okyanus",
    "Ozeane": "Okyanuslar",
    "Strand": "Plaj",
    "Strände": "Plajlar",
    "Insel": "Ada",
    "Inseln": "Adalar",
    "Wüste": "Çöl",
    "Wüsten": "Çöller",
    "Stein": "Taş",
    "Steine": "Taşlar",
    "Sand": "Kum",
    "Erde": "Toprak",
    "Boden": "Zemin",
    "Böden": "Zeminler",
    "Himmel": "Gökyüzü",
    "Wolke": "Bulut",
    "Wolken": "Bulutlar",
    "Sonne": "Güneş",
    "Mond": "Ay",
    "Stern": "Yıldız",
    "Sterne": "Yıldızlar",
    "Weltraum": "Uzay",
    "Universum": "Evren",
    "Welt": "Dünya",
    "Erde": "Dünya",
    "Natur": "Doğa",
    "Umwelt": "Çevre",
    "Klima": "İklim",
    "Wetter": "Hava",
    "Landschaft": "Manzara",
    "Landschaften": "Manzaralar",
    "Aussicht": "Manzara",
    "Aussichten": "Manzaralar",
}

# German stopwords to skip (no useful standalone meaning)
GERMAN_STOPWORDS = {
    "der", "die", "das", "den", "dem", "des", "ein", "eine", "einer", "eines", "einem", "einen",
    "und", "oder", "aber", "denn", "sondern", "weil", "wenn", "als", "ob", "dass", "daß",
    "in", "an", "auf", "mit", "zu", "zur", "zum", "von", "vom", "bei", "beim", "für",
    "über", "unter", "vor", "nach", "neben", "zwischen", "durch", "ohne", "um",
    "aus", "ab", "bis", "gegen", "trotz", "während", "wegen", "statt",
    "so", "wie", "auch", "noch", "nur", "schon", "sehr", "mehr", "wieder", "immer",
    "man", "etwas", "nichts", "alles", "viel", "viele", "wenig", "wenige",
    "ja", "nein",
    "u", "a", "z", "b", "ca", "s", "t",
    "dieser", "diese", "dieses", "dies", "jener", "jene", "jenes",
    "welcher", "welche", "welches", "welchen",
    "ihrer", "seiner", "meiner", "deiner", "unserer", "eurer",
    "welche", "werden", "werde", "wirst", "werdet", "wurde", "wurdest", "wurden", "wurdet",
    "sein", "seid", "war", "warst", "waren", "wart",
    "haben", "habe", "hast", "habt", "hatte", "hattest", "hatten", "hattet",
    "können", "kann", "kannst", "könnt", "konnte", "konntest", "konnten", "konntet",
    "müssen", "muss", "musst", "müsst", "musste", "musstest", "mussten", "musstet",
    "sollen", "soll", "sollst", "sollt", "sollte", "solltest", "sollten", "solltet",
    "wollen", "will", "willst", "wollt", "wollte", "wolltest", "wollten", "wolltet",
    "mögen", "mag", "magst", "mögt", "mochte", "mochtest", "mochten", "mochtet",
    "dürfen", "darf", "darfst", "dürft", "durfte", "durftest", "durften", "durftet",
}


def clean_token(t: str) -> str:
    """Strip surrounding punctuation from a token."""
    return re.sub(r'^[^\wäöüÄÖÜß]+|[^\wäöüÄÖÜß]+$', '', t)


def is_useful_german(w: str) -> bool:
    if not w:
        return False
    if len(w) < 2:
        return False
    if w.isdigit():
        return False
    if re.fullmatch(r'[^\wäöüÄÖÜß]+', w):
        return False
    if w.lower() in GERMAN_STOPWORDS:
        return False
    return True


def tokenize(s: str):
    return [clean_token(t) for t in s.split()]


# ─────────── JSON traversal helpers (same as before) ───────────
def walk_brief(data):
    out = []
    root = data.get("Brief_Kaliplari", {})
    for cat, items in root.items():
        if not isinstance(items, list):
            continue
        for entry in items:
            if isinstance(entry, dict) and "Almanca" in entry and "Türkçe" in entry:
                out.append((cat, entry["Almanca"], entry["Türkçe"]))
    return out


def walk_bild(data):
    out = []
    root = data.get("Bildbeschreibung_kalıpları", {})
    for cat, items in root.items():
        if not isinstance(items, list):
            continue
        for entry in items:
            if isinstance(entry, dict) and "Almanca" in entry and "Türkçe" in entry:
                out.append((cat, entry["Almanca"], entry["Türkçe"]))
    return out


def walk_erfahrung(data):
    out = []
    def visit(node, cat_hint):
        if isinstance(node, dict):
            if "Almanca" in node and "Türkçe" in node:
                a = node["Almanca"]
                t = node["Türkçe"]
                if isinstance(a, str) and isinstance(t, str):
                    out.append((cat_hint, a, t))
                elif isinstance(a, list) and isinstance(t, list):
                    for i in range(min(len(a), len(t))):
                        out.append((cat_hint, a[i], t[i]))
                return
            if "Örnekler" in node and isinstance(node["Örnekler"], list):
                for e in node["Örnekler"]:
                    if isinstance(e, dict) and "Almanca" in e and "Türkçe" in e:
                        out.append((cat_hint, e["Almanca"], e["Türkçe"]))
                return
            for k, v in node.items():
                if isinstance(v, (dict, list)):
                    visit(v, k if isinstance(v, dict) and "Örnekler" in v else cat_hint)
        elif isinstance(node, list):
            for item in node:
                visit(item, cat_hint)
    visit(data.get("B1_BILDBESCHREIBUNG_ERFAHRUNG", {}), "Erfahrung")
    return out


CAT_MAP = {
    "Giris_Kalip_Cümleleri": "giris",
    "Yardim_Isteme_Cümleleri": "yardim-isteme",
    "Birine_Yardim_Cümleleri": "yardim-etme",
    "Durum_Ifade_Etme_Cümleleri": "durum",
    "Davet_Cümleleri": "davet",
    "Davet_Kabul_Etme": "davet-kabul",
    "Davet_Kabul_Etmeme_Ozür_Dileme": "davet-red",
    "Teşekkür_Kalıpları": "tesekkur",
    "Gelişme_Cümleleri": "gelisme",
    "Şikayet": "sikayet",
    "Görev_Hatırlatma": "gorev",
    "Garanti": "garanti",
    "Bilgi_İsteme": "bilgi-isteme",
    "Hızlı_Çözüm": "hizli-cozum",
    "Bilgi_Verme": "bilgi-verme",
    "Tebrik": "tebrik",
    "Tamir_Tamirci": "tamir",
    "Yeni_Ürün_veya_Para_İsteme": "yeni-urun",
    "Yardımcı_Olunmazsa": "yardimci-olmazsa",
    "Feshetme_Teyit_Etme": "feshetme",
    "İrtibat": "irtibat",
    "Hastalık": "hastalik",
    "Talep": "talep",
    "Termin": "termin",
    "Ödeme": "odeme",
    "Süre": "sure",
    "Cevap_Bekleme": "cevap-bekleme",
    "Hediye": "hediye",
    "Soru_Sorma": "soru-sorma",
    "Temel_Gözlemler": "bildbeschreibung",
    "Kişisel_Bağlantılar": "bildbeschreibung",
    "Kültürel_Karşılaştırmalar": "bildbeschreibung",
    "Mekan_Bilgileri": "bildbeschreibung",
    "Mevsim_Bilgileri": "bildbeschreibung",
    "Duygu_Durumları": "bildbeschreibung",
    "Arka_Plan_Bilgileri": "bildbeschreibung",
    "Fotoğraf_Değerlendirmeleri": "bildbeschreibung",
    "Yaş_Tahminleri": "bildbeschreibung",
    "Atmosfer_Bilgileri": "bildbeschreibung",
    "Zaman_Bilgileri": "bildbeschreibung",
    "Önemli_Konular": "bildbeschreibung",
    "Hava_Durumu_Tahminleri": "bildbeschreibung",
    "Vorstellung": "deneyim",
    "İşinize_Geldiği_Gibi_Konuşun": "deneyim",
    "Aileden_Biri_Üzerine_Konuşmak": "deneyim",
    "Basit_Cümleler_Kullanın": "deneyim",
    "Maymuncuk_Cümleler": "maymuncuk",
    "Güncel_Konular": "deneyim",
    "Her_Konudan_Kalıp_Cümleler": "deneyim",
    "Diğer_Kalıp_Cümleler": "deneyim",
    "Kişisel_Deneyimler": "deneyim",
    "Erfahrung": "deneyim",
}

def norm_cat(raw):
    return CAT_MAP.get(raw, "diger")


def main():
    brief_path = UPLOAD / "brief.json"
    bild_path = UPLOAD / "bild.json"
    erfahrung_path = UPLOAD / "bild-erfahrung.json"

    all_pairs = []
    with open(brief_path, encoding="utf-8") as f:
        all_pairs.extend(walk_brief(json.load(f)))
    with open(bild_path, encoding="utf-8") as f:
        all_pairs.extend(walk_bild(json.load(f)))
    with open(erfahrung_path, encoding="utf-8") as f:
        all_pairs.extend(walk_erfahrung(json.load(f)))

    print(f"Total sentence pairs: {len(all_pairs)}")

    # Pass 1: collect all unique German words appearing in the sentences
    word_to_cats = {}  # word_lower -> (display_form, set_of_cats)
    for cat_raw, ger_sent, tr_sent in all_pairs:
        if isinstance(ger_sent, list):
            ger_sent = " ".join(str(x) for x in ger_sent)
        if not isinstance(ger_sent, str):
            continue
        for tok in tokenize(ger_sent):
            if not is_useful_german(tok):
                continue
            key = tok  # preserve original case for display
            lower = tok.lower()
            if lower not in word_to_cats:
                word_to_cats[lower] = (key, set())
            word_to_cats[lower][1].add(norm_cat(cat_raw))

    print(f"Unique useful German words found in sentences: {len(word_to_cats)}")

    # Pass 2: build the word-pair list using the curated dictionary
    # Prefer the case form that matches the dictionary key exactly.
    result = []
    seen_lower = set()
    miss_count = 0
    for lower, (display, cats) in word_to_cats.items():
        # Try exact case match first
        tr = GERMAN_TR_DICT.get(display)
        if not tr:
            # Try lowercase
            tr = GERMAN_TR_DICT.get(lower)
        if not tr:
            # Try capitalized first letter
            cap = display[0].upper() + display[1:]
            tr = GERMAN_TR_DICT.get(cap)
        if not tr:
            miss_count += 1
            continue
        if lower in seen_lower:
            continue
        seen_lower.add(lower)
        # Pick the first category (alphabetical) as primary
        cat = sorted(cats)[0] if cats else "diger"
        result.append({
            "id": "",
            "german": display,
            "turkish": tr,
            "category": cat,
        })

    print(f"Words matched to translations: {len(result)}")
    print(f"Words skipped (no translation): {miss_count}")

    # Sort by category then alphabetical
    result.sort(key=lambda x: (x["category"], x["german"].lower()))
    for i, item in enumerate(result, start=1):
        item["id"] = f"v{i}"

    out_obj = {
        "_meta": {
            "source_files": ["upload/brief.json", "upload/bild.json", "upload/bild-erfahrung.json"],
            "description": "Bu dosya brief.json, bild.json ve bild-erfahrung.json dosyalarındaki cümlelerin içinden çıkarılan bireysel Almanca kelimelerini içerir. Türkçe karşılıkları küratörlü bir B1 seviye sözlükten gelir. Orijinal JSON dosyaları değiştirilmemiştir.",
            "extraction_method": "Tokenize German sentences -> filter stopwords/punctuation -> lookup Turkish translation in curated B1 dictionary",
            "total_words": len(result),
        },
        "words": result,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(out_obj, f, ensure_ascii=False, indent=2)
    print(f"Wrote: {OUT}")

    # Print category breakdown
    from collections import Counter
    cats = Counter(w["category"] for w in result)
    print("Category breakdown:")
    for c, n in cats.most_common():
        print(f"  {c:25} {n}")


if __name__ == "__main__":
    main()
